Adding libs, functions & tests for API tests
vs-odessa/PythonAutomationTraining pull request #4
Opened 2019-05-29 14:20 UTC by vstepanov-lohika-tix

![image](https://user-images.githubusercontent.com/48280294/58564674-0ed20300-8236-11e9-82e8-3b1c36cdbe5a.png)

2019-05-29 14:54 UTC, archick12 commented on api/jira_actions.py
> +        return None
You are hiding root cause of failure, this will increase time for debug.

2019-05-29 14:59 UTC, archick12 commented on api/jira_actions.py
> +        return ""
The empty string may lead to confusion if the name of json attribute will change.
Better to avoid "try catch" with empty return statement or add more verbose error message.

2019-05-29 15:19 UTC, archick12 commented on tests_api/test_search_issues.py
> +        assert response.json()["total"] == 0
Please, check status code

2019-05-29 15:20 UTC, archick12 commented on api/jira_api_client.py
> +def jira_get_request(url, params=None):
I see that content of 'jira_get_request' and 'jira_post_request' is similar. Could you reduce code duplication?

2019-05-29 15:21 UTC, archick12 requested changes
Good job, please, update code

2019-05-30 09:36 UTC, archick12 commented on tests_api/test_update_issues.py
> +        assert updated_issue.json()["fields"]["assignee"] == None
Please, check the real value of the status code instead of overriding it with None value.

2019-05-30 11:08 UTC, vstepanov-lohika-tix commented on api/jira_api_client.py
> +def jira_get_request(url, params=None):
Right, fixed

2019-05-30 11:10 UTC, vstepanov-lohika-tix commented on tests_api/test_update_issues.py
> +        assert updated_issue.json()["fields"]["assignee"] == None
I got a correct 200 response with a key value that is really None there

2019-05-30 11:12 UTC, vstepanov-lohika-tix commented on api/jira_actions.py
> +        return None
Fixed message

2019-05-30 11:27 UTC, archick12 approved these changes
Great Job!

2019-05-30 11:28 UTC, merged